config/routes.rb
Certifeasy::Application.routes.draw do

  devise_for :users
  resources :certifs do
    member do
       put :valider
       put :invalider
    end
  end

  resources :users, :only=>[:index, :show,:edit,:update]
  resources :roles

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :firstname, :lastname, :dob, :street, :zipcode, :town, :country, :role_ids, :certifs_attributes

  validates_presence_of :firstname, :lastname, :email
  validates_uniqueness_of :email, :case_sensitive => false

  #Relation
  has_and_belongs_to_many :roles
  has_many :certifs, :dependent => :destroy
  accepts_nested_attributes_for :certifs, :allow_destroy => true

  def role?(role)
    return !!self.roles.find_by_name(role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.where('id <> ?', current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    1.times {@user.certifs.build}
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
    <%= f.error_messages %>
    <p>
      <%= f.label :firstname %><br/>
      <%= f.text_field :firstname %>
    </p>
    <p>
      <%= f.label :lastname %><br/>
      <%= f.text_field :lastname %>
    </p>
    <p>
      <%= f.label :dob %><br/>
      <%= f.date_select :dob %>
    </p>
    <p>
      <%= f.label :street %><br/>
      <%= f.text_field :street %>
    </p>
    <p>
      <%= f.label :zipcode %><br/>
      <%= f.text_field :zipcode %>
    </p>
    <p>
      <%= f.label :town %><br/>
      <%= f.text_field :town %>
    </p>
    <p>
      <%= f.label :country %><br/>
      <%= f.text_field :country %>
    </p>

    <div class="newPaperclipFiles">

      <%= f.fields_for :certifs do |certif_fields| %>

          <% if certif_fields.object.new_record? %>
              <%= certif_fields.file_field :attachment %> <br/>
          <% end %>

      <% end %>

    </div>

    <div class="existingPaperclipFiles">

          <%= f.fields_for :certifs do |certif_fields| %>

              <% unless certif_fields.object.new_record? %>
                <div class="links">
                    <%= certif_fields.check_box :_destroy %>
                    <%= link_to certif_fields.object.attachment_file_name, certif_fields.object.attachment.url %>
                </div>
               <% end %>

          <% end %>
    </div>


    <p>
      <%= f.label :role %><br/>
      <%= f.collection_select :role_ids, Role.all, :id, :name_humanize %>
    </p>

    <p><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Editer utilisateur" %>

<%= render 'form' %>

<p>
  <%= link_to "Voir", @user %> |
  <%= link_to "Voir tous", users_path %>
</p>

app/views/users/index.html.erb
<% title "Tableau de bord" %>

<% if can? :manage, @users %>
    <table>
      <tr>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Email</th>
        <th>Date de naissance</th>
        <th>Rue</th>
        <th>Code postal</th>
        <th>Ville</th>
        <th>Pays</th>
      </tr>
      <% for user in @users %>
          <tr>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.email %></td>
            <td><%= user.dob %></td>
            <td><%= user.street %></td>
            <td><%= user.zipcode %></td>
            <td><%= user.town %></td>
            <td><%= user.country %></td>
            <td><%= link_to "Voir", user %></td>
            <td><%= link_to "Editer", edit_user_path(user) %></td>
          </tr>
      <% end %>
    </table>

    <p>
    <%= link_to "Roles", roles_path %>
    </p>

<% else %>
    <p>Vous ne pouvez pas voir le tableau de bord des utlisateurs</p>
<% end %>

app/views/users/new.html.erb
<% title "Nouvel utilisateur" %>

<%= render 'form' %>

<p><%= link_to "Retour à la liste", users_path %></p>

app/views/users/show.html.erb
<% title "Utilisateur" %>

<p>
  <strong>Prénom:</strong>
  <%= @user.firstname %>
</p>
<p>
  <strong>Nom:</strong>
  <%= @user.lastname %>
</p>
<p>
  <strong>Date de naissance:</strong>
  <%= @user.dob %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Rue:</strong>
  <%= @user.street %>
</p>
<p>
  <strong>Code postal:</strong>
  <%= @user.zipcode %>
</p>
<p>
  <strong>Ville:</strong>
  <%= @user.country %>
</p>
</p>
<% if can? :manage, @users %>
    <p>
      <strong>Role:</strong>
      <ul>
      <% @user.roles.each do |role| %>
            <li><%= role.name.humanize %></li>
      <% end %>
      </ul>
    </p>
    <p>
      <strong>Certificats:</strong>
    <ul>
    <% @user.certifs.each do |certif| %>
            <li>
              <%= link_to certif.attachment_file_name, certif.attachment.url %>
              <%= button_to "Invalider certificat", invalider_certif_path(certif), :method => :put %>
              <%= button_to "Valider certificat", valider_certif_path(certif), :method => :put %>
            </li>
    <% end %>
    </ul>
    </p>
<% end %>


<p>
  <%= link_to "Editer", edit_user_path(@user) %> |
  <%= link_to "Voir tous", users_path %>
</p>