config/routes.rb
Certifeasy::Application.routes.draw do

  devise_for :users
  resources :certifs do
    member do
       put :valider
       put :invalider
    end
  end

  resources :users, :only=>[:index, :show,:edit,:update]
  resources :roles

  root :to => 'home#index'

end

app/models/certif.rb
class Certif < ActiveRecord::Base
  belongs_to :user
  has_attached_file :attachment

  # Paperclip Validations
  validates_attachment_content_type :attachment, :content_type => ['application/pdf']
  validates_attachment_size :attachment, :less_than => 1.megabytes

end

app/controllers/certifs_controller.rb
class CertifsController < ApplicationController

  def index
    @certifs_invalides = Certif.find(:all, :conditions => "valid_until IS NULL")
    @certifs_valides = Certif.find(:all, :conditions => "valid_until IS NOT NULL")
  end

  def show
    @certif = Certif.find(params[:id])
    respond_to do |format|
      format.json { render :json => @certif }
    end
  end

  def new
    @certif = Certif.new
  end

  def create
    @certif = Certif.new(params[:certif])
    if @certif.save
      redirect_to @certif, :notice => "Successfully created certif."
    else
      render :action => 'new'
    end
  end

  def edit
    @certif = Certif.find(params[:id])
  end

  def update
    @certif = Certif.find(params[:id])
    if @certif.update_attributes(params[:certif])
      redirect_to @certif, :notice  => "Successfully updated certif."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @certif = Certif.find(params[:id])
    @certif.destroy
    redirect_to certifs_url, :notice => "Successfully destroyed certif."
  end

  def valider
    @certif = Certif.find(params[:id])
    @certif.update_attribute :valid_until, Time.now
    redirect_to certifs_path , :notice => "Certificat valide."
  end

  def invalider
    @certif = Certif.find(params[:id])
    @certif.update_attribute :valid_until, nil
    redirect_to certifs_path , :notice => "Certificat invalide."
  end
end

app/helpers/certifs_helper.rb
module CertifsHelper
end

app/views/certifs/_form.html.erb
<%= form_for @certif do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </p>
  <p>
    <%= f.label :attachment_file_name %><br />
    <%= f.text_field :attachment_file_name %>
  </p>
  <p>
    <%= f.label :attachment_content_type %><br />
    <%= f.text_field :attachment_content_type %>
  </p>
  <p>
    <%= f.label :attachment_file_size %><br />
    <%= f.number_field :attachment_file_size %>
  </p>
  <p>
    <%= f.label :attachment_updated_at %><br />
    <%= f.datetime_select :attachment_updated_at %>
  </p>
  <p>
    <%= f.label :valid_unitl %><br />
    <%= f.date_select :valid_until %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/certifs/edit.html.erb
<% title "Edit Certif" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @certif %> |
  <%= link_to "View All", certifs_path %>
</p>

app/views/certifs/index.html.erb
<% title "Certifs" %>

<h2>Certificats non validés</h2>
<% if not @certifs_invalides.empty? %>
    <table>
      <tr>
        <th>User email</th>
        <th>Certificat</th>
        <th>Valid</th>
      </tr>
      <% for certif in @certifs_invalides %>
          <tr>
            <td><%= certif.user.email %></td>
            <td><%= link_to certif.attachment_file_name, certif.attachment.url, :target => "_blank" %></td>
            <td><%= certif.valid_until %></td>
            <td><%= link_to "Show", certif %></td>
            <td><%= link_to "Edit", edit_certif_path(certif) %></td>
            <td><%= link_to "Destroy", certif, :confirm => 'Are you sure?', :method => :delete %></td>
            <td><%= button_to "Valider certificat", valider_certif_path(certif), :method => :put, :class => 'btn success' %></td>
          </tr>
      <% end %>
    </table>
<% else %>
    <i>Aucun certificat non validé.</i>
<% end %>


<h2>Certificats validés</h2>
<% if not @certifs_valides.empty? %>
    <table>
      <tr>
        <th>User email</th>
        <th>Certificat</th>
        <th>Valid</th>
      </tr>
      <% for certif in @certifs_valides %>
          <tr>
            <td><%= certif.user.email %></td>
            <td><%= link_to certif.attachment_file_name, certif.attachment.url, :target => "_blank" %></td>
            <td><%= certif.valid_until %></td>
            <td><%= link_to "Show", certif %></td>
            <td><%= link_to "Edit", edit_certif_path(certif) %></td>
            <td><%= link_to "Destroy", certif, :confirm => 'Are you sure?', :method => :delete %></td>
            <td><%= button_to "Invalider certificat", invalider_certif_path(certif), :method => :put, :class => 'btn danger' %></td>
          </tr>
      <% end %>
    </table>
<% else %>
    <i>Aucun certificat validé.</i>
<% end %>

app/views/certifs/new.html.erb
<% title "New Certif" %>

<%= render 'form' %>

<p><%= link_to "Back to List", certifs_path %></p>

app/views/certifs/show.html.erb
<% title "Certif" %>

<p>
  <strong>User:</strong>
  <%= @certif.user_id %>
</p>
<p>
  <strong>Attachment File Name:</strong>
  <%= @certif.attachment_file_name %>
</p>
<p>
  <strong>Attachment Content Type:</strong>
  <%= @certif.attachment_content_type %>
</p>
<p>
  <strong>Attachment File Size:</strong>
  <%= @certif.attachment_file_size %>
</p>
<p>
  <strong>Attachment Updated At:</strong>
  <%= @certif.attachment_updated_at %>
</p>
<p>
  <strong>Valid:</strong>
  <%= @certif.valid_until %>
</p>

<p>
  <%= link_to "Valider certificat", complete_certif_path(@certif), :confirm => 'Are you sure?' %> |
  <%= link_to "Edit", edit_certif_path(@certif) %> |
  <%= link_to "Destroy", @certif, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", certifs_path %>
</p>